services:
  - type: web
    name: isl-sign-detector
    env: python
    runtime: python-3.11.9
    plan: free
    buildCommand: |
      pip install --upgrade pip && 
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.server:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 30
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
    healthCheckPath: /health
    disk:
      name: isl-data
      mountPath: /opt/render/project/data
      sizeGB: 1